version: '3.7'

services:
  parser:
    build:
      context: .
    volumes:
      # - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - webnet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - parser
    ports:
      - 4000:4000
    networks:
      - webnet
networks:
  webnet:
